name: Build & Release LinHT Docker Images
on:
  release:
    types: [published]

env:
  REGISTRY: ghcr.io

jobs:
  build-and-push-x64:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Extract metadata
        id: meta
        run: |
          OWNER_LC="${{ github.repository_owner }}"
          REPO_NAME=$(echo "${{ github.repository }}" | cut -d'/' -f2)
          echo "owner=${OWNER_LC,,}" >> $GITHUB_OUTPUT
          echo "repo=${REPO_NAME,,}" >> $GITHUB_OUTPUT
          echo "tag=${GITHUB_REF_NAME}" >> $GITHUB_OUTPUT

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push LinHT x64 image
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64
          push: true
          tags: ${{ env.REGISTRY }}/${{ steps.meta.outputs.owner }}/${{ steps.meta.outputs.repo }}:${{ steps.meta.outputs.tag }}-amd64
          cache-from: type=gha,scope=linht-amd64
          cache-to: type=gha,mode=max,scope=linht-amd64

      - name: Export LinHT x64 image
        run: |
          docker pull ${{ env.REGISTRY }}/${{ steps.meta.outputs.owner }}/${{ steps.meta.outputs.repo }}:${{ steps.meta.outputs.tag }}-amd64
          docker save ${{ env.REGISTRY }}/${{ steps.meta.outputs.owner }}/${{ steps.meta.outputs.repo }}:${{ steps.meta.outputs.tag }}-amd64 -o linht-x64.tar

      - name: Upload LinHT x64 artifact
        uses: actions/upload-artifact@v4
        with:
          name: linht-docker-x64
          path: linht-x64.tar
          retention-days: 1

  build-and-push-arm64:
    runs-on: ubuntu-24.04-arm
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Extract metadata
        id: meta
        run: |
          OWNER_LC="${{ github.repository_owner }}"
          REPO_NAME=$(echo "${{ github.repository }}" | cut -d'/' -f2)
          echo "owner=${OWNER_LC,,}" >> $GITHUB_OUTPUT
          echo "repo=${REPO_NAME,,}" >> $GITHUB_OUTPUT
          echo "tag=${GITHUB_REF_NAME}" >> $GITHUB_OUTPUT

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push LinHT arm64 image
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/arm64
          push: true
          tags: ${{ env.REGISTRY }}/${{ steps.meta.outputs.owner }}/${{ steps.meta.outputs.repo }}:${{ steps.meta.outputs.tag }}-arm64
          cache-from: type=gha,scope=linht-arm64
          cache-to: type=gha,mode=max,scope=linht-arm64

      - name: Export LinHT arm64 image
        run: |
          docker pull ${{ env.REGISTRY }}/${{ steps.meta.outputs.owner }}/${{ steps.meta.outputs.repo }}:${{ steps.meta.outputs.tag }}-arm64
          docker save ${{ env.REGISTRY }}/${{ steps.meta.outputs.owner }}/${{ steps.meta.outputs.repo }}:${{ steps.meta.outputs.tag }}-arm64 -o linht-arm64.tar

      - name: Upload LinHT arm64 artifact
        uses: actions/upload-artifact@v4
        with:
          name: linht-docker-arm64
          path: linht-arm64.tar
          retention-days: 1

  upload-release-assets:
    needs: [build-and-push-x64, build-and-push-arm64]
    runs-on: ubuntu-latest
    if: github.event_name == 'release'
    steps:
      - name: Download LinHT x64 artifact
        uses: actions/download-artifact@v4
        with:
          name: linht-docker-x64
          path: ./artifacts/

      - name: Download LinHT arm64 artifact
        uses: actions/download-artifact@v4
        with:
          name: linht-docker-arm64
          path: ./artifacts/

      - name: Upload LinHT release assets
        uses: softprops/action-gh-release@v2
        with:
          files: |
            ./artifacts/linht-x64.tar
            ./artifacts/linht-arm64.tar
